---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diploma-app
  labels:
    app.kubernetes.io/name: diploma-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: diploma-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: diploma-app
    spec:
      containers:
      - name: diploma-app
        image: roma4edu/diploma_app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: diploma-app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: diploma-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001